### ISSUE TITLE
ModuleNotFoundError: No module named 'pwd'

### ISSUE THREAD

**Issue by Nyconing** [jowinjohnchemban/winbinwalk#7]
Run the created exe got error:

Traceback (most recent call last):
  File "c:\users\nyconing\appdata\local\programs\python\python37-32\Scripts\binwalk", line 4, in <module>
    __import__('pkg_resources').run_script('binwalk==2.3.3', 'binwalk')
  File "C:\Users\Nyconing\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Users\Nyconing\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pkg_resources\__init__.py", line 1472, in run_script
    exec(code, namespace, namespace)
  File "c:\users\nyconing\appdata\local\programs\python\python37-32\lib\site-packages\binwalk-2.3.3-py3.7.egg\EGG-INFO\scripts\binwalk", line 2, in <module>
    from binwalk.__main__ import main
  File "C:\Users\Nyconing\AppData\Local\Programs\Python\Python37-32\lib\site-packages\binwalk-2.3.3-py3.7.egg\binwalk\__main__.py", line 24, in <module>
    import binwalk.modules
  File "C:\Users\Nyconing\AppData\Local\Programs\Python\Python37-32\lib\site-packages\binwalk-2.3.3-py3.7.egg\binwalk\modules\__init__.py", line 16, in <module>
    from binwalk.modules.extractor import Extractor
  File "C:\Users\Nyconing\AppData\Local\Programs\Python\Python37-32\lib\site-packages\binwalk-2.3.3-py3.7.egg\binwalk\modules\extractor.py", line 7, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'

**Comment by Arthurfogo7** [comment]
That happened to me too

**Comment by goodiesohhi** [comment]
pwd is linux only, I guess binwalk has changed to now require that module

**Comment by seifhassine** [comment]
> What's the last version that works on Windows?

At this point i think it's easier to just run a linux vm
